### ISSUE TITLE
Compilation issue with 0.52

### ISSUE THREAD

**Issue by uggla** [ponceto/xcpc#1]
Hi Olivier,

Some trouble to compile XCPC 0.52 from git sources.
So far, I have not looked for the reason but is used to compile before.
To be honest, I'm a bit lazy today, and I'm pretty sure you will give me the answer quickly as it looks like something related to autotools black magic.

We can also notice that gtk4 is not found despite gtk4-devel being installed.
It's probably a missing dependency; anyway, it can use gtk3 instead atm.

Cmd line log attached:
[xcpc.log](https://github.com/user-attachments/files/16570274/xcpc.log)

**Comment by ponceto** [comment]
Gtk4 is currently not supported. The support is prepared into the build chain, but Xcpc is not ported to gtk4 because this toolkit does not give access to the underlying X11 handles anymore.

Please use gtk3 as toolkit, as described in the documentation.

Gtk4 will come soon 👌

**Comment by ponceto** [comment]
You can also download and install precompiled deb if you are using a debian related distro

**Comment by uggla** [comment]
I saw some gtk4 folders, so I thought it was supported hence the mistake.

I'm a Fedora user, so I'd like to compile from src so that I can eventually make an RPM.

Any idea about the compilation issue ?

**Comment by uggla** [comment]
There's something wrong about the naming from .c to .cc.
It looks for .c files that are not available.

To progress I made an ugly hack I have made 2 sylinks libxcpc.c ⇒ libxcpc.cc and  xlib.c ⇒ xlib.cc and it manages to go to the end of the compilation.

I will look later if I manage to find the real root cause. But I'm sure you'll tell me what's wrong before.

But so far it starts. :+1: 
![image](https://github.com/user-attachments/assets/63110da3-b0ea-43b8-8960-fe5977d171c3)

**Comment by ponceto** [comment]
Don't understand why you had to do these symlinks. The naming seems to be goodin the repo

**Comment by ponceto** [comment]
Have you cloned correctly the repo? Or used the tarball? It's weird because everything is fine in the repo.

Have you made a clean build from scratch?

**Comment by uggla** [comment]
You are correct.

First, I updated my old repo and switched to tag: `xcpc-0.52.0`.
I did:
```
make clean
git reset --hard
git clean -f
git status
```
Making sure everything was clean. But I might have miss something.

Because right now, I used a fresh `git clone` and it works perfectly. I feel a little dumb...

Sorry for the inconvenience, and thanks for your help.

**Comment by ponceto** [comment]
Great to hear my friend ❤️
